### ISSUE TITLE
Sorry, acquisition timeout! when using Sqlite

### ISSUE THREAD

**Issue by TheBlindM** [quarkiverse/quarkus-jdbc-sqlite#33] opened 2022-09-08 06:52 UTC
Describe the bug
2022-09-08 13:12:35,306 ERROR [com.exa.con.ErrHandle] (executor-thread-1) ??? to handle request: javax.persistence.PersistenceException: org.hibernate.HibernateException: Could not apply work
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:762)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:742)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.persist(TransactionScopedSession.java:144)
	at org.hibernate.engine.spi.SessionLazyDelegator.persist(SessionLazyDelegator.java:241)
	at org.hibernate.Session_5b93bee577ae2f8d76647de04cfab36afbf52958_Synthetic_ClientProxy.persist(Unknown Source)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:99)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:94)
	at io.quarkus.hibernate.orm.panache.PanacheEntityBase.persist(PanacheEntityBase.java:53)
	at com.example.service.ShortcutCmdService.lambda$update$10(ShortcutCmdService.java:172)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.example.service.ShortcutCmdService.update(ShortcutCmdService.java:172)
	at com.example.service.ShortcutCmdService_Subclass.update$$superforward1(Unknown Source)
	at com.example.service.ShortcutCmdService_Subclass$$function$$4.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:49)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.example.service.ShortcutCmdService_Subclass.update(Unknown Source)
	at com.example.service.ShortcutCmdService_ClientProxy.update(Unknown Source)
	at com.example.controller.ShortcutCmdController.update(ShortcutCmdController.java:61)
	at com.example.controller.ShortcutCmdController_Subclass.update$$superforward1(Unknown Source)
	at com.example.controller.ShortcutCmdController_Subclass$$function$$3.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.example.controller.ShortcutCmdController_Subclass.update(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hibernate.HibernateException: Could not apply work
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doInNewTransaction(JtaIsolationDelegate.java:156)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.access$200(JtaIsolationDelegate.java:31)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate$1.call(JtaIsolationDelegate.java:67)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doInSuspendedTransaction(JtaIsolationDelegate.java:113)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.delegateWork(JtaIsolationDelegate.java:57)
	at org.hibernate.id.enhanced.TableStructure$1.getNextValue(TableStructure.java:137)
	at org.hibernate.id.enhanced.NoopOptimizer.generate(NoopOptimizer.java:40)
	at org.hibernate.id.enhanced.SequenceStyleGenerator.generate(SequenceStyleGenerator.java:534)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:115)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:185)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:128)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:756)
	... 78 more
Caused by: org.hibernate.exception.GenericJDBCException: unable to obtain isolated JDBC connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doTheWork(JtaIsolationDelegate.java:192)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.access$000(JtaIsolationDelegate.java:31)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate$1$1.call(JtaIsolationDelegate.java:63)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doInNewTransaction(JtaIsolationDelegate.java:144)
	... 91 more
Caused by: java.sql.SQLException: Sorry, acquisition timeout!
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:307)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:248)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doTheWork(JtaIsolationDelegate.java:170)
	... 94 more
Expected behavior
No response

Actual behavior
quarkus.datasource.jdbc.max-size=1
quarkus.datasource.jdbc.initial-size=1

When I increase the max-size, there will be a database lock,When max-size is 1, Sorry, acquisition timeout

code:
image

How to Reproduce?
No response

Output of uname -a or ver
windows 10

Output of java -version
java17

GraalVM version (if different from Java)
No response

Quarkus version or git rev
2.11.2.Final

Build tool (ie. output of mvnw --version or gradlew --version)
mvnw

Additional information
No response

**Comment by alexeysharandin** [comment] 2022-09-08 11:34
@TheBlindM 
could you please share some reproducer in github? in your stacktrace - nothing about sqlite available here.
Checked internally memory/file mode with your properties - works both with unit tests

**Comment by alexeysharandin** [comment] 2022-09-08 12:55
https://github.com/TheBlindM/SpliteTest/blob/master/server/src/main/java/com/example/service/ShortcutCmdService.java#L110-L119

I see different code in your repo

**Comment by alexeysharandin** [comment] 2022-09-08 14:47
Creating shortcut over:
http://localhost:10218/shortcutCmd/
POST: { "name": "Name"}

Update over http://localhost:10218/shortcutCmd/1
PUT
 {
    "id": 1,
    "name": "new name"
}

both working...
I think need steps to reproduce

**Comment by alexeysharandin** [comment] 2022-09-08 19:30
The problem - because multiple write operations executed in one transaction. Not sure what it's supported but will check additionally.

In your case:
```java
    public boolean update(UpdShortcutCmdDTO updShortcutCmdDTO) throws SystemException, NotSupportedException, HeuristicRollbackException, HeuristicMixedException, RollbackException {

        Integer shortcutCmdId = updShortcutCmdDTO.id();
        List<Integer> shortcutCmdGroupIdList = updShortcutCmdDTO.shortcutCmdGroupIdList();
        ShortcutCmd shortcutCmd = ShortcutCmd.<ShortcutCmd>findByIdOptional(shortcutCmdId).orElseThrow(() -> new WebApplicationException(shortcutCmdId + "不存在"));
        updShortcutCmdDTO.copyProperty(shortcutCmd);
        userTransaction.begin();
        GroupShortcutCmd.delete("shortcutCmdId = ?1", shortcutCmdId);
        userTransaction.commit();

        if (CollectionUtil.isNotEmpty(shortcutCmdGroupIdList)) {
            shortcutCmdGroupIdList.stream().map((shortcutCmdGroupId) -> {
                GroupShortcutCmd groupShortcutCmd = new GroupShortcutCmd();
                groupShortcutCmd.setShortcutCmdId(shortcutCmdId);
                groupShortcutCmd.setShortcutCmdGroupId(shortcutCmdGroupId);
                return groupShortcutCmd;
            }).forEach(groupShortcutCmd -> {
                try {
                    userTransaction.begin();
                    groupShortcutCmd.persist();
                    userTransaction.commit();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }



        List<UpdShortcutCmdImplDTO> addShortcutCmdImplDTOList = updShortcutCmdDTO.shortcutCmdImplList();
        if (CollectionUtil.isNotEmpty(addShortcutCmdImplDTOList)) {
            for (UpdShortcutCmdImplDTO addShortcutCmdImplDTO : addShortcutCmdImplDTOList) {
                ShortcutCmdImpl shortcutCmdImpl = addShortcutCmdImplDTO.convert();
                shortcutCmdImpl.setShortcutCmdId(shortcutCmdId);
                userTransaction.begin();
                shortcutCmdImpl.persist();
                userTransaction.commit();
                List<Integer> osTypeIdList = addShortcutCmdImplDTO.shortcutCmdOsTypeIdList();
                userTransaction.begin();
                ShortcutCmdImplOsType.delete("shortcutCmdImplId = ?1", shortcutCmdId);
                userTransaction.commit();
                if (CollectionUtil.isNotEmpty(osTypeIdList)) {
                    osTypeIdList.forEach(osTypeId -> {
                                try {
                                    userTransaction.begin();
                                    ShortcutCmdImplOsType
                                            .builder()
                                            .osTypeId(osTypeId)
                                            .shortcutCmdImplId(shortcutCmdImpl.id)
                                            .build()
                                            .persist();
                                    userTransaction.commit();
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }
                    );

                }
            }
        }
        return true;
    }
``` 
This works

**Closed as completed** 2022-09-09 08:25 UTC
